resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3abac84d0fbac67d5a4e1abd07d22a4c73841c61ef523da81bfc04844c3cbc40
  name: controller
  newName: us.gcr.io/my-repo/my-project/controller-image
