# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/memcached-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

# images:
# - name: controller:latest
#   newName: "{{ controller_image }}"
#   newTag: "{{ controller_image_digest }}"

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: memcached-operator.v0.0.0
    namespace: placeholder
  #nginx:1.21.0
  patch: |-
      - op: replace
        path: /spec/relatedImages/0/image
        value: {{ related_image_controller }}    
      - op: replace
        path: /spec/relatedImages/1/image
        value: {{ related_image_first }}    
      - op: replace
        path: /spec/relatedImages/2/image
        value: {{ related_image_second }}
      - op: replace
        path: /spec/replaces
        value: {{ replaces_version }}
      - op: replace
        path: /metadata/annotations/olm.skipRange
        value: {{ skips_versions }}
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  patch: |-
    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/containers/1/volumeMounts/0
    # Remove the "cert" volume, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/volumes/0
